/*
 * generated by Xtext 2.10.0
 */
package com.gantsign.restrulz.idea.completion

import com.gantsign.restrulz.idea.lang.RestdslLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class RestdslCompletionContributor extends AbstractRestdslCompletionContributor {
	new() {
		this(RestdslLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
