/*
 * generated by Xtext 2.10.0
 */
package com.gantsign.restrulz.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class RestdslIdeaModule extends AbstractRestdslIdeaModule {
}
