/*
 * generated by Xtext 2.10.0
 */
package com.gantsign.restrulz.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class RestdslIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new RestdslStandaloneSetupIdea().createInjector
	}

}
