/*
 * generated by Xtext 2.10.0
 */
package com.gantsign.restrulz.idea.lang


class RestdslFileType extends AbstractRestdslFileType {
	public static final RestdslFileType INSTANCE = new RestdslFileType()
	
	new() {
		super(RestdslLanguage.INSTANCE)
	}
}
