/*
 * generated by Xtext 2.10.0
 */
package com.gantsign.restrulz


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RestdslStandaloneSetup extends RestdslStandaloneSetupGenerated {

	def static void doSetup() {
		new RestdslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
